stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/preprocessed
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/preprocessed
    - src/feature_engineering.py
    outs:
    - data/final
  model_building:
    cmd: python src/model_training.py
    deps:
    - data/preprocessed
    - src/model_training.py
    params:
    - model_training.n_estimators
    - model_training.max_depth
    - model_training.max_leaves
    - model_training.grow_policy
    outs:
    - models/grid_model.pkl
    - models/xgboost_model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - models/grid_model.pkl
    - models/xgboost_model.pkl
    - src/model_evaluation.py
    metrics:
    - results/metrics.json
