stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    # params:
    # - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/preprocessed
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/preprocessed
    - src/feature_engineering.py
    # params:
    # - feature_engineering.max_features
    outs:
    - data/preprocessed
  model_building:
    cmd: python src/model_training.py
    deps:
    - data/preprocessed
    - src/model_training.py
    # params:
    # - model_building.n_estimators
    # - model_building.random_state
    outs:
    - models/grid_model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - models/grid_model.pkl
    - src/model_evaluation.py
    metrics:
    - results/metrics.json
